// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'D:/Code/GinBi-main/GinBI-frontend/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import BarChartOutlined
  from 'D:/Code/GinBi-main/GinBI-frontend/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import PieChartOutlined
  from 'D:/Code/GinBi-main/GinBI-frontend/node_modules/@ant-design/icons/es/icons/PieChartOutlined';
import AliwangwangOutlined
  from 'D:/Code/GinBi-main/GinBI-frontend/node_modules/@ant-design/icons/es/icons/AliwangwangOutlined';
import CrownOutlined from 'D:/Code/GinBi-main/GinBI-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';

export default {HomeOutlined, BarChartOutlined, PieChartOutlined, AliwangwangOutlined, CrownOutlined};
