// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import {HelmetProvider} from 'D:/Code/GinBi-main/GinBI-frontend/node_modules/@umijs/renderer-react';
import {context} from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, {context}, container);
}
