export default [
  {
    path: '/user', layout: false, routes: [
      {path: '/user/login', component: './User/Login'},
      {path: '/user/register', component: './User/Register'},
      {path: '/user/settings', component: './User/Settings'},
    ]
  },
  {path: '/', redirect: '/welcome'},
  {path: '/welcome', name: '首页', icon: 'homeOutlined', component: './Welcome', access: 'canUser'},
  {path: '/add_chart', name: '智能分析', icon: 'barChart', component: './AddChart', access: 'canUser'},
  {path: '/add_chart/:fileId?', component: './AddChart', access: 'canUser'},
  {path: '/add_chart_async', name: '智能分析（异步）', icon: 'barChart', component: './AddChartAsync', access: 'canUser'},
  {path: '/add_chart_async/:fileId?', component: './AddChartAsync', access: 'canUser'},
  {path: '/add_chart_MQ', name: '智能分析（MQ）', icon: 'barChart', component: './AddChartMQ', access: 'canUser'},
  {path: '/add_chart_MQ/:fileId?', component: './AddChartMQ', access: 'canUser'},
  {path: '/my_chart', name: '我的图表', icon: 'pieChart', component: './MyChart', access: 'canUser'},
  {path: '/my_data_source', name: '我的数据源', icon: 'fileText', component: './MyDataSource', access: 'canUser'},
  {path: '/recharge', name: '积分充值', icon: 'walletOutlined', component: './Recharge', access: 'canUser'},
  {path: '/chart_detail/:id', component: './ChartDetail', access: 'canUser'},
  {path: '/story', name: 'AI聊天室', icon: 'AliwangwangOutlined', component: './story', access: 'canUser'},
  {path: '/admin/dashboard', name: '数据看板', icon: 'dashboard', component: './Admin/Dashboard', access: 'canAdmin'},
  {path: '/admin/user', name: '用户管理', icon: 'team', component: './Admin/UserManage', access: 'canAdmin'},
  {path: '/admin/chart', name: '图表管理', icon: 'barChart', component: './Admin/ChartManage', access: 'canAdmin'},
  {path: '/admin/ai', name: 'AI对话管理', icon: 'message', component: './Admin/AiManage', access: 'canAdmin'},
  {path: '/admin/ai-config', name: 'AI配置管理', icon: 'setting', component: './Admin/AiConfig', access: 'canAdmin'},
  {path: '/admin/points', name: '积分管理', icon: 'wallet', component: './Admin/PointsManage', access: 'canAdmin'},
  {path: '/admin/monitor', name: '系统监控', icon: 'monitor', component: './Admin/Monitor', access: 'canAdmin'},
  {path: '/admin/logs', name: '操作日志', icon: 'fileText', component: './Admin/Logs', access: 'canAdmin'},
  {path: '/admin/file', name: '文件管理', icon: 'folderOutlined', component: './Admin/FileManage', access: 'canAdmin'},
  {path: '*', layout: false, component: './404'},
];